desc 'Compile the project'
  platform :android do
    lane :build do |options|
    nuget_restore(
      project_path: 'App1.sln'
    )
    
    app_version(
      solution_path: 'App1.sln',
      version: ENV['VERSION_NAME'],
      build: ENV['BUILD_NUMBER'],
    )

    keystore_path = ENV['ANDROID_KEYSTORE']
    keystore_password = ENV['STORE_PASSWORD']
    key_alias= ENV['KEY_ALIAS']
    key_alias_password = ENV['KEY_ALIAS_PASSWORD']
    android_project_path = ENV['PWD'] + '/App1/App1.Droid/App1.Droid.csproj'
    
    sh("msbuild /p:Configuration=Release -t:SignAndroidPackage /p:AndroidKeyStore=True /p:AndroidSigningKeyStore=#{keystore_path} /p:AndroidSigningStorePass=#{keystore_password} /p:AndroidSigningKeyAlias=#{key_alias} /p:AndroidSigningKeyPass=#{key_alias_password} #{android_project_path}")
    
    supply(
      aab: ENV['PWD'] + '/App1/App1.Droid/bin/Release/com.shedeed.myapp-Signed.aab',
      package_name: 'com.shedeed.myapp',
      track: 'alpha', # upload to alpha, we can promote it later
      json_key: ENV['GOOGLE_JSON_FILE'],
      release_status: 'draft',
    )
    end
  end